<div class="login">
	<h1>Cadastrar</h1>
    <form method="post" id="formCadastro" action="" onSubmit="verificarUsuario()";>
    	<input type="text" id="usuario" name="usuario" placeholder="Usuario" class="usuario" value="<?=$this->usuario?>"required="required" />
        <input type="password" id="senha" name="senha" placeholder="Senha" class="senha" value="<?=$this->senha?>" required="required" />
        <input type="password" name="confirmarsenha" placeholder="Confirmar Senha"  class="confirmarsenha" required="required" /> 
        <input type="submit"  class="btn btn-primary btn-block btn-large" id="login"  value="Realizar Cadastro"  />

    </form>
    
</div>  

<script type="text/javascript">

/*data='<?= json_encode($value) ?>'
$(document).on('submit', '#login', function(){
  
      $('input[name="usuario"]').val('');
      $('input[name="senha"]').val('');  
      $("#formCadastro");
       
          
});*/

    function verificarUsuario(){
      $(document).on('submit', '#login', function(){
      let usuario =  $('input[name="usuario"]').val('');
      let senha = $('input[name="senha"]').val('');
      let confirmarsenha = $(".confirmarsenha").val();
      
        if(senha == confirmarsenha){
          $.ajax({
            url:'<?=$this->url(["go"=>"user","action"=>"add"])?>',
            type:'POST',
            data: {id:id},
            success:function(resultado){
              if(resultado == 0){
                alert("Usuario já Cadastrado");
              }else{
                alert("Cadastro realizado com sucesso!!!");
                window.location="<?=$this->url(["go"=>"index","action"=>"index"])?>";
              }
              
            }
          });
          
        }else{
        alert("As senhas não são iguais");
        }
    });    
    }

</script> 